name: PlatformIO

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./esp8266-hunter-sprinkler
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: PlatformIO Run
        uses: karniv00l/platformio-run-action@v1
        with:
          environments: "d1_mini"
          targets: "d1_mini_pro"
          silent: false
          verbose: true
          disable-auto-clean: false
